version: '3.7'
services:
  service:
    image: integrations-platform-offline-product-catalog
    container_name: integrations-platform-offline-product-catalog
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "1234:1234"
networks:
  compose-network:
    driver: bridge